### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by ritesh94** [cesards/CropImageView#26]
```
 <com.cesards.cropimageview.CropImageView
                android:id="@+id/iv_profile_pic"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:foreground="@drawable/gradient_bottom_top"
                android:src="@drawable/add_profile_picbkg"
                app:crop="centerTop"
                /> 
```

**This is what I get when I start activity:**
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
                                                                          at com.cesards.cropimageview.CropImageView.computeImageMatrix(CropImageView.java:119)
                                                                          at com.cesards.cropimageview.CropImageView.setFrame(CropImageView.java:107)
                                                                          at android.view.View.layout(View.java:16648)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                          at android.view.View.layout(View.java:16651)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                          at android.os.Handler.handleCallback(Handler.java:746)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by Ok-Alex** [comment]
Having same issue

**Comment by cesards** [comment]
Could you provide more information? 
- Device
- OS version?

**Comment by tpnet** [comment]
@cesards  I found the problem. If you don't set up SRC, you will have this problem.

**Comment by cesards** [comment]
@tpnet what device and android os version are you using guys?

**Comment by david-serrano** [comment]
this is still happening, even with XML layout inflation instead of programmatic creation

**Comment by cesards** [comment]
I'm going to work on a new version of the library. Sorry because I've got a lot of side work and I haven't been able to maintain it properly. Thanks for the info!

**Comment by cesards** [comment]
Fixed in the next release
